# Generated by Django 3.2.4 on 2021-06-20 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_comment_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
