# Generated by Django 3.2.4 on 2021-06-20 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_comment_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'managed': True},
        ),
    ]
