# Generated by Django 3.2.4 on 2021-06-20 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_comment_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
