# Generated by Django 3.2.4 on 2021-06-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_comment_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_complete',
        ),
        migrations.AddField(
            model_name='task',
            name='is_complete',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
