# Generated by Django 3.2.4 on 2021-06-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210621_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_by_email',
            new_name='created_by',
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3')], max_length=2),
        ),
    ]
